export const persons = [
  {
    id: "1",
    first_name: "Welliton",
    last_name: "Da Costa",
    birthdate: new Date("2001-01-25T00:00:00Z"),
    rut: "25036291-9",
    address: "Alonso de sotomayor 4320",
    phone: "+56962273789",
    gender: "Male",
    email: "wellintoncosta.10@hotmail.com",
    active: true,
    registered: new Date(),
    city: "Santiago",
    commune: "Providencia",
    has_passport: 1,
    gender_id: 1, // Assume 1 represents Male in the application
    notes: "Some notes about Welliton",
    disablement_date: null,
    disablement_user_id: null,
    social_name: "Welliton",
    created_at: new Date(),
    updated_at: new Date(),
    patient: {
      id: "1",
      active: true,
      created_at: new Date(),
      person_id: "1",
    },
    professional: null,
  },
];
